services:
  - type: web
    name: puribunga2-web
    env: docker
    plan: free # or 'starter' if you need more resources
    region: singapore # Adjust based on your preference
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromContext: git.url
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: puribunga2-db
          property: connectionString

databases:
  - name: puribunga2-db
    plan: free # or 'starter'
    databaseName: puri_bunga2
    user: admin
    region: singapore
